# Generated by Django 5.1.4 on 2025-01-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.BigIntegerField()),
                ('type', models.CharField(choices=[('BA', 'konto bankowe'), ('CA', 'gotówka'), ('CO', 'bony'), ('AN', 'inne')], default='konto bankowe', max_length=50)),
                ('currency_code', models.CharField(choices=[('PLN', 'złotówki'), ('USD', 'dolary'), ('EUR', 'euro')], default='PLN', max_length=3)),
                ('description', models.TextField(max_length=512)),
                ('number', models.CharField(default=None, max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Money Account',
            },
        ),
    ]
