# Generated by Django 5.1.4 on 2025-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.BigIntegerField()),
                ('currency_id', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=512)),
                ('number', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Money Account',
            },
        ),
    ]
