# Generated by Django 5.1.4 on 2025-04-09 15:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyaccount',
            name='number',
        ),
        migrations.AddField(
            model_name='moneyaccount',
            name='possibly_negative',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='currency_code',
            field=models.CharField(choices=[('EUR', 'EUR'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', max_length=3),
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('INC', 'Przychód'), ('EXP', 'Wydatek')], max_length=3)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='monkey_budget.maincategory')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.BigIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Transaction total value must be nonnegative')])),
                ('transaction_direction', models.CharField(choices=[('IN', 'przychód'), ('OUT', 'wydatek')], default='OUT', max_length=3)),
                ('balance_after_transaction', models.BigIntegerField(default=0, editable=False)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='monkey_budget.moneyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SubTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Subtransaction amount value must be nonnegative')])),
                ('description', models.CharField(blank=True, max_length=100)),
                ('main_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtransactions', to='monkey_budget.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the user registered', null=True, verbose_name='IP Address')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user registered', verbose_name='Registration Date')),
                ('user_agent', models.TextField(blank=True, help_text='Browser and system information of the user', verbose_name='User Agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Registration Data',
                'verbose_name_plural': 'User Registration Data',
            },
        ),
    ]
