# Generated by Django 5.1.4 on 2025-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0002_remove_moneyaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyaccount',
            name='currency_code',
            field=models.CharField(choices=[('EUR', 'EUR'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', max_length=3),
        ),
    ]
