# Generated by Django 5.1.4 on 2025-04-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0002_remove_moneyaccount_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtransactions', to='monkey_budget.subcategory', verbose_name='Kategoria'),
        ),
    ]
