# Generated by Django 5.1.4 on 2025-02-18 21:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0003_alter_moneyaccount_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Transaction total value must be nonnegative')])),
                ('transaction_direction', models.CharField(choices=[('IN', 'income'), ('OUT', 'outcome')], default='OUT', max_length=3)),
                ('balance_after_transaction', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='monkey_budget.moneyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SubTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Transaction total value must be nonnegative')])),
                ('description', models.CharField(blank=True, max_length=100)),
                ('main_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_transaction', to='monkey_budget.transaction')),
            ],
        ),
    ]
