# Generated by Django 5.1.4 on 2025-02-21 22:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0004_transaction_subtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtransaction',
            name='amount',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Subtransaction amount must be nonnegative')]),
        ),
        migrations.AlterField(
            model_name='subtransaction',
            name='main_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtransactions', to='monkey_budget.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.BigIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Transaction total value must be nonnegative')]),
        ),
    ]
