# Generated by Django 5.1.6 on 2025-03-16 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0004_transaction_subtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyaccount',
            name='possibly_negative',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.BigIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Transaction total value must be nonnegative')]),
        ),
    ]
