# Generated by Django 5.1.4 on 2025-03-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0004_maincategory_subcategory'),
        ('monkey_budget', '0004_transaction_subtransaction'),
    ]

    operations = [
    ]
