# Generated by Django 5.1.6 on 2025-03-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0005_merge_20250316_1900'),
        ('monkey_budget', '0005_moneyaccount_possibly_negative_and_more'),
    ]

    operations = [
    ]
