# Generated by Django 5.1.4 on 2025-03-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0006_alter_subtransaction_main_transaction_and_more'),
        ('monkey_budget', '0006_merge_20250317_1809'),
    ]

    operations = [
    ]
