# Generated by Django 5.1.4 on 2025-03-20 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0007_merge_20250319_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtransaction',
            name='amount',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Subtransaction amount value must be nonnegative')]),
        ),
    ]
