# Generated by Django 5.1.7 on 2025-03-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_budget', '0006_alter_transaction_balance_after_transaction_and_more'),
        ('monkey_budget', '0008_alter_subtransaction_amount'),
    ]

    operations = [
    ]
